# Generated by Django 2.2.12 on 2021-12-27 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_title', models.CharField(max_length=100)),
                ('task_content', models.TextField(blank=True)),
                ('created_date', models.DateField(default='2021-12-27')),
            ],
            options={
                'ordering': ['-created_date'],
            },
        ),
    ]
